# Generated by Django 3.1.1 on 2020-10-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('croppingtool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crop',
            new_name='cpp',
        ),
    ]
